import type { ModuleInfo, Listing } from './types'

export const modules: ModuleInfo[] = [
  {
    id: 'talent',
    title: 'نیروی انسانی',
    description: 'رزومه متخصصین و نیازهای نیروی پروژه',
    color: '#f59e0b',
    colorRgb: '245, 158, 11',
    count: 4,
    icon: 'users',
  },
  {
    id: 'contractor',
    title: 'پیمانکاران',
    description: 'پیمانکاران اجرایی، مشاوره و خدمات',
    color: '#38bdf8',
    colorRgb: '56, 189, 248',
    count: 3,
    icon: 'hard-hat',
  },
  {
    id: 'equipment',
    title: 'ماشین‌آلات و تجهیزات',
    description: 'اجاره و فروش ماشین‌آلات سنگین و تجهیزات',
    color: '#facc15',
    colorRgb: '250, 204, 21',
    count: 0,
    icon: 'truck',
  },
  {
    id: 'goods',
    title: 'کالا و تأمین',
    description: 'کالاها و اقلام بخش تأمین (Procurement)',
    color: '#2dd4bf',
    colorRgb: '45, 212, 191',
    count: 0,
    icon: 'package',
  },
  {
    id: 'technical',
    title: 'نیازمندی‌های تکنیکال',
    description: 'دوره‌ها، نرم‌افزارها، استانداردها و منابع فنی',
    color: '#a78bfa',
    colorRgb: '167, 139, 250',
    count: 1,
    icon: 'graduation-cap',
  },
]

export const listings: Listing[] = [
  {
    id: '1',
    module: 'talent',
    title: 'مدیر کارگاه',
    side: 'offer',
    tags: ['مهندسی عمران', '۱۲ سال', 'تمام‌وقت', 'کارشناسی ارشد'],
    location: 'خوزستان',
    price: '۲۰۰',
    priceUnit: 'میلیون تومان',
    timeAgo: '۵ ساعت پیش',
    experience: '۱۲ سال',
    education: 'کارشناسی ارشد',
    employmentType: 'تمام‌وقت',
  },
  {
    id: '2',
    module: 'technical',
    title: 'آموزش پریمورا P6',
    side: 'offer',
    tags: ['نرم‌افزار', 'مدیریت پروژه', 'آنلاین', '۱۰۰'],
    location: 'تهران',
    price: '۵۰۰,۰۰۰',
    priceUnit: 'تومان',
    timeAgo: '۵ ساعت پیش',
  },
  {
    id: '3',
    module: 'contractor',
    title: 'طاعتی',
    side: 'offer',
    tags: ['خدمات', 'سایر', 'بدون رتبه', '۱۲ سال'],
    location: 'خوزستان',
    timeAgo: '۶ ساعت پیش',
  },
  {
    id: '4',
    module: 'talent',
    title: 'دفتر فنی پایپینگ',
    side: 'offer',
    tags: ['مهندسی مکانیک', 'پروژه‌ای', 'کارشناسی'],
    location: 'اصفهان',
    timeAgo: '۲ روز پیش',
  },
  {
    id: '5',
    module: 'talent',
    title: 'سرپرست برنامه‌ریزی و کنترل پروژه',
    side: 'offer',
    tags: ['برنامه‌ریزی و کنترل پروژه', '۱۲ سال', 'تمام‌وقت'],
    location: 'خوزستان',
    price: '۱۵۰',
    priceUnit: 'میلیون تومان',
    timeAgo: '۲ روز پیش',
  },
]
